### ISSUE TITLE
Vertaisarviointi #1

### ISSUE THREAD

**Issue by nikitaessine** [KeranenKirill/OT-P#1]
Projekti ladattu 25.7 klo 8.00

# Onnistumiset
Työ on lähtenyt hyvin käyntiin ja ensimmäiset toiminnalisuudet rakennettu.
- Hyvin kommentoitua koodia
- Jaettu omiin moduuleihin
- Tietokanta otettu käyttöön
- Vaatimusmäärittely esitelty asianmukaisesti
- Salaiset tiedostot piilotettu .env tiedostoon

# Prannusehdotus
Muutamassa html-tiedostoissa koodi alkaa *titile* -sanalla tai *forms* -sanalla. Esimerkiksi näin:

```html
<title>.TsirpTsirp.</title>
<h1>Hello!</h1>

{% if session.user_id %}
Tsirp Tsirp! You are logged in!
<a href="/logout">Log out</a>

{% else %}
<a href="/login">Log in</a>
{% endif %}
```
Tämän voisi laittaa kokonaiseen muotoon:

```html
<!DOCTYPE html>
<html>
<head>
    <title>.TsirpTsirp.</title>
</head>
<body>
    <h1>Hello!</h1>

    {% if session.user_id %}
    <p>Tsirp Tsirp! You are logged in!</p>
    <a href="/logout">Log out</a>

    {% else %}
    <a href="/login">Log in</a>
    {% endif %}
</body>
</html>

```

**Comment by keranenkirill** [comment]
korjaukset: https://github.com/KeranenKirill/OT-P/commit/3f636c5c6598c0e058b8040f4c3e4c3ec63c5814
